

--
-- Name: contact_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_identities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    contact_id uuid NOT NULL,
    channel_id uuid NOT NULL,
    external_id text NOT NULL
);


--
-- Name: contact_labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_labels (
    contact_id uuid NOT NULL,
    label_id uuid NOT NULL
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contacts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text,
    email text,
    phone text,
    locale text DEFAULT 'id'::text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    external_id text
);


--
-- Name: csat_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.csat_responses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    thread_id uuid,
    message_id uuid,
    score integer,
    feedback text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT csat_responses_score_check CHECK (((score >= 1) AND (score <= 5)))
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    content text,
    metadata jsonb,
    embedding public.vector(1536)
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.documents_id_seq OWNED BY public.documents.id;


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    ai_profile_id uuid,
    bucket text NOT NULL,
    path text NOT NULL,
    filename text NOT NULL,
    mime_type text,
    byte_size bigint,
    checksum text,
    uploaded_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.labels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    scope public.label_scope NOT NULL,
    name text NOT NULL,
    color text
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    thread_id uuid NOT NULL,
    direction public.message_direction,
    role public.message_role DEFAULT 'user'::public.message_role NOT NULL,
    type public.message_type DEFAULT 'text'::public.message_type NOT NULL,
    body text,
    payload jsonb,
    actor_kind text,
    actor_id uuid,
    seq bigint NOT NULL,
    in_reply_to uuid,
    edited_at timestamp with time zone,
    edit_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_direction_vs_type CHECK ((((type = ANY (ARRAY['event'::public.message_type, 'note'::public.message_type])) AND (direction IS NULL)) OR ((type <> ALL (ARRAY['event'::public.message_type, 'note'::public.message_type])) AND (direction IS NOT NULL)))),
    CONSTRAINT messages_actor_kind_check CHECK ((actor_kind = ANY (ARRAY['customer'::text, 'agent'::text, 'ai'::text, 'system'::text])))
);


--
-- Name: messages_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: n8n_chat_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.n8n_chat_histories (
    id integer NOT NULL,
    session_id character varying(255) NOT NULL,
    message jsonb NOT NULL
);


--
-- Name: n8n_chat_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.n8n_chat_histories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: n8n_chat_histories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.n8n_chat_histories_id_seq OWNED BY public.n8n_chat_histories.id;


--
-- Name: n8n_webhook_routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.n8n_webhook_routes (
    route_key text NOT NULL,
    n8n_url text NOT NULL,
    secret_current text NOT NULL,
    key_version integer DEFAULT 1 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: openai_usage_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.openai_usage_snapshots (
    id bigint NOT NULL,
    captured_at timestamp with time zone DEFAULT now() NOT NULL,
    range_label text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    input_tokens bigint DEFAULT 0 NOT NULL,
    output_tokens bigint DEFAULT 0 NOT NULL,
    total_tokens bigint DEFAULT 0 NOT NULL,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: openai_usage_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.openai_usage_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: openai_usage_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.openai_usage_snapshots_id_seq OWNED BY public.openai_usage_snapshots.id;


--
-- Name: org_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_members (
    org_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text DEFAULT 'agent'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT org_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'agent'::text])))
);


--
-- Name: org_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_settings (
    org_id uuid NOT NULL,
    default_locale text DEFAULT 'id'::text,
    retention_days integer DEFAULT 90,
    ai_default_profile_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: orgs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orgs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    plan text DEFAULT 'free'::text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: permission_bundles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission_bundles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    resource text NOT NULL,
    action text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: rbac_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rbac_policies (
    role_id uuid NOT NULL,
    policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: role_bundles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_bundles (
    role_id uuid NOT NULL,
    bundle_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: super_agent_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.super_agent_members (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    super_agent_id uuid NOT NULL,
    agent_user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT super_agent_not_self CHECK ((super_agent_id <> agent_user_id))
);


--
-- Name: thread_collaborators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.thread_collaborators (
    thread_id uuid NOT NULL,
    user_id uuid NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.threads (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    contact_id uuid,
    channel_id uuid NOT NULL,
    status public.thread_status DEFAULT 'open'::public.thread_status NOT NULL,
    assignee_user_id uuid,
    last_msg_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    assigned_by_user_id uuid,
    resolved_by_user_id uuid,
    ai_handoff_at timestamp with time zone,
    assigned_at timestamp with time zone,
    resolved_at timestamp with time zone,
    is_blocked boolean DEFAULT false NOT NULL,
    ai_access_enabled boolean DEFAULT true NOT NULL,
    notes text,
    additional_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    resolution text,
    end_reason text,
    handover_reason text,
    auto_resolve_at timestamp with time zone,
    CONSTRAINT handover_reason_taxonomy CHECK (((handover_reason IS NULL) OR (handover_reason = ANY (ARRAY['ambiguous'::text, 'payment'::text, 'policy'::text])) OR (handover_reason ~~ 'other:%'::text)))
);


--
-- Name: COLUMN threads.auto_resolve_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.threads.auto_resolve_at IS 'Timestamp when this thread should be auto-closed due to inactivity after an agent/assistant reply.';


--
-- Name: token_balances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_balances (
    org_id uuid NOT NULL,
    balance_tokens bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: token_topups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_topups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    amount_tokens bigint NOT NULL,
    reason text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT token_topups_amount_tokens_check CHECK ((amount_tokens > 0))
);


--
-- Name: token_usage_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_usage_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    thread_id uuid,
    model text NOT NULL,
    provider text DEFAULT 'openai'::text NOT NULL,
    prompt_tokens integer NOT NULL,
    completion_tokens integer NOT NULL,
    total_tokens integer NOT NULL,
    status text DEFAULT 'ok'::text NOT NULL,
    error_code text,
    made_at timestamp with time zone DEFAULT now() NOT NULL,
    meta jsonb DEFAULT '{}'::jsonb,
    user_id uuid,
    channel_id uuid,
    message_id uuid
);


--
-- Name: twofa_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twofa_challenges (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    channel text NOT NULL,
    code_hash text NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    CONSTRAINT twofa_challenges_channel_check CHECK ((channel = 'email'::text))
);