-- Migration: Strict Sync of Messages Table Policies
-- Generated by Antigravity to perfectly match Development environment.

-- 1. Add missing "anon_messages_update_by_account"
-- This policy exists in Dev (role: public) and was missing in Main.
-- It works alongside "anon_update_messages_by_account" (role: anon).
DROP POLICY IF EXISTS "anon_messages_update_by_account" ON public.messages;
CREATE POLICY "anon_messages_update_by_account" ON public.messages
FOR UPDATE TO public
USING (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND t.account_id IS NOT NULL
    AND t.account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', '')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND t.account_id IS NOT NULL
    AND t.account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', '')
  )
);

-- 2. Sync Authenticated Update Policy
-- Dev has "update messages perm" (Simple permission check).
-- Main had "messages update perm update_own" (Ownership check).
-- We align with Dev's simplified model.
DROP POLICY IF EXISTS "messages update perm update_own" ON public.messages;
DROP POLICY IF EXISTS "update messages perm" ON public.messages;

CREATE POLICY "update messages perm" ON public.messages
FOR UPDATE TO authenticated
USING (has_perm('update', 'message'))
WITH CHECK (has_perm('update', 'message'));

-- Note: Dev uses singular 'message' in has_perm for this specific policy.
-- Keeping it exact to Dev as requested.

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
