-- Migration: Fix and Consolidate Messages Update Policies
-- Generated by Antigravity to resolve persistence issues for LiveChat attachments.

-- 1. Drop existing conflicting/overlapping policies
DROP POLICY IF EXISTS "anon_messages_update_by_account" ON public.messages;
DROP POLICY IF EXISTS "anon_update_messages_by_account" ON public.messages;

-- 2. Create single, robust UPDATE policy
-- Allows update if request header 'x-account-id' matches EITHER:
-- a) The thread's account_id column (Strict)
-- b) The thread's additional_data->'account_id' (Relaxed/Legacy)
CREATE POLICY "anon_messages_update_by_account" ON public.messages
FOR UPDATE TO public
USING (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND (
      -- Match against column
      (t.account_id IS NOT NULL AND t.account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', ''))
      OR
      -- Match against additional_data
      (t.additional_data ->> 'account_id' = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', ''))
    )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND (
      -- Match against column
      (t.account_id IS NOT NULL AND t.account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', ''))
      OR
      -- Match against additional_data
      (t.additional_data ->> 'account_id' = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', ''))
    )
  )
);

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
