-- Migration: Sync Channels Table Policies to match Development
-- Generated by Antigravity to resolve policy discrepancy found during full audit.

-- 1. Sync DELETE policy
-- Dev: "channels delete perm delete" (Simple 'delete' permission check).
-- Main: "channels delete perm delete_own" (Enforces super_agent_id = auth.uid()).
-- Dev allows anyone with 'delete' permission on 'channels' to delete.
DROP POLICY IF EXISTS "channels delete perm delete_own" ON public.channels;
DROP POLICY IF EXISTS "channels delete perm delete" ON public.channels;

CREATE POLICY "channels delete perm delete" ON public.channels
FOR DELETE TO authenticated
USING (has_perm('delete', 'channels'));

-- 2. Sync SELECT policy
-- Dev: "channels select perm super agent and members" (Uses can_access_super_scope).
-- Main: "channels select perm read_own" (Enforces super_agent_id = auth.uid()).
-- Dev allows team members (Master Agents?) to read channels if they are in the scope.
DROP POLICY IF EXISTS "channels select perm read_own" ON public.channels;
DROP POLICY IF EXISTS "channels select perm super agent and members" ON public.channels;

CREATE POLICY "channels select perm super agent and members" ON public.channels
FOR SELECT TO authenticated
USING (
  super_agent_id IS NOT NULL 
  AND can_access_super_scope(super_agent_id)
);

-- Note: "channels select perm read_all" matches on both.

-- 3. Sync UPDATE policy
-- Dev: "update channel" (Simple 'update' permission check).
-- Main: "channels update perm update_own" (Enforces super_agent_id = auth.uid()).
DROP POLICY IF EXISTS "channels update perm update_own" ON public.channels;
DROP POLICY IF EXISTS "update channel" ON public.channels;

CREATE POLICY "update channel" ON public.channels
FOR UPDATE TO authenticated
USING (has_perm('update', 'channels'));

-- Note: INSERT policy matches ("channels insert perm create").

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
