-- Migration: Add missing LiveChat schema and policies (Gap Fill)
-- Generated by Antigravity

-- 1. Ensure Schema Definitions match DB
ALTER TABLE public.threads ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE public.threads ADD COLUMN IF NOT EXISTS additional_data JSONB DEFAULT '{}'::jsonb;

-- Index for performance on lookups
CREATE INDEX IF NOT EXISTS threads_account_id_idx ON public.threads (account_id);
CREATE INDEX IF NOT EXISTS threads_channel_id_idx ON public.threads (channel_id);

-- 2. RLS Policies for Guest Access (LiveChat)
-- LiveChat uses 'x-account-id' header for authentication/identification of guests.

-- 2.1 Threads: Allow guests to find their own threads
DROP POLICY IF EXISTS "anon_threads_by_account" ON public.threads;
CREATE POLICY "anon_threads_by_account" ON public.threads
FOR SELECT TO anon
USING (
  -- Check standard column
  account_id = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')::uuid
  OR
  -- Check JSONB field (fallback)
  (additional_data->>'account_id') = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')
);

-- 2.2 Messages: Allow guests to read messages in their threads
DROP POLICY IF EXISTS "anon_messages_by_account" ON public.messages;
CREATE POLICY "anon_messages_by_account" ON public.messages
FOR SELECT TO anon
USING (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND (
      t.account_id = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')::uuid
      OR
      (t.additional_data->>'account_id') = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')
    )
  )
);

-- 2.3 Messages: Allow guests to insert new messages
-- This is technically handled by webhook, but we add it to match Development environment policies.
DROP POLICY IF EXISTS "anon_messages_insert_by_account" ON public.messages;
CREATE POLICY "anon_messages_insert_by_account" ON public.messages
FOR INSERT TO anon
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND t.account_id IS NOT NULL
    AND t.account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', '')
  )
);

-- 2.3.1 Threads: Allow guests to insert new threads
DROP POLICY IF EXISTS "anon_threads_insert_by_account" ON public.threads;
CREATE POLICY "anon_threads_insert_by_account" ON public.threads
FOR INSERT TO public
WITH CHECK (
  account_id IS NOT NULL
  AND account_id::text = COALESCE(current_setting('request.headers', true)::jsonb ->> 'x-account-id', '')
);

-- 2.4 Messages: Allow guests to UPDATE their own messages (e.g. attaching file_link)
DROP POLICY IF EXISTS "anon_update_messages_by_account" ON public.messages;
CREATE POLICY "anon_update_messages_by_account" ON public.messages
FOR UPDATE TO anon
USING (
  -- Must be a message in a thread they own
  EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND (
      t.account_id = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')::uuid
      OR
      (t.additional_data->>'account_id') = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')
    )
  )
  -- And they should probably only update messages they created (role='user') but the thread check is the strong gate.
)
WITH CHECK (
   EXISTS (
    SELECT 1 FROM public.threads t
    WHERE t.id = public.messages.thread_id
    AND (
      t.account_id = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')::uuid
      OR
      (t.additional_data->>'account_id') = (current_setting('request.headers', true)::jsonb ->> 'x-account-id')
    )
  )
);

-- Reload schema cache to ensure policies take effect immediately
NOTIFY pgrst, 'reload schema';
