-- Migration: Sync Messages Table Policies to match Development
-- Generated by Antigravity to resolve policy discrepancy reported by user.

-- 1. Sync INSERT policy (Relax to match Dev)
-- Main had strict checks. Dev has `auth.uid() IS NOT NULL`.
DROP POLICY IF EXISTS "messages insert perm create" ON public.messages;
CREATE POLICY "messages insert perm create" ON public.messages
FOR INSERT TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

-- 2. Sync SELECT policy (Use scope function like Dev)
-- Main used verbose "messages select perm read_collaborator".
-- Dev uses "messages select perm read super agent thread" with `can_access_message_scope`.
DROP POLICY IF EXISTS "messages select perm read_collaborator" ON public.messages;
DROP POLICY IF EXISTS "messages select perm read super agent thread" ON public.messages;

CREATE POLICY "messages select perm read super agent thread" ON public.messages
FOR SELECT TO authenticated
USING (can_access_message_scope(thread_id));

-- 3. Add missing UPDATE policy for file links (from Dev)
-- This supports the JWT/Channel Secret flow for generic updates if headers aren't used.
DROP POLICY IF EXISTS "anon_messages_update_file_link" ON public.messages;
CREATE POLICY "anon_messages_update_file_link" ON public.messages
FOR UPDATE TO anon
USING (
  EXISTS (
     SELECT 1 FROM public.threads t
     JOIN public.channels c ON c.id = t.channel_id
     WHERE t.id = public.messages.thread_id
     AND c.provider = 'web'
     AND COALESCE(c.is_active, true)
     AND c.secret_token IS NOT NULL
     AND c.secret_token = (current_setting('request.jwt.claims', true)::jsonb ->> 'channel_secret')
     AND t.id = ((current_setting('request.jwt.claims', true)::jsonb ->> 'thread_id')::uuid)
  )
)
WITH CHECK (
  EXISTS (
     SELECT 1 FROM public.threads t
     JOIN public.channels c ON c.id = t.channel_id
     WHERE t.id = public.messages.thread_id
     AND c.provider = 'web'
     AND COALESCE(c.is_active, true)
     AND c.secret_token IS NOT NULL
     AND c.secret_token = (current_setting('request.jwt.claims', true)::jsonb ->> 'channel_secret')
     AND t.id = ((current_setting('request.jwt.claims', true)::jsonb ->> 'thread_id')::uuid)
  )
);

-- 4. Sync UPDATE policy naming/logic
-- Dev has "update messages perm". Main has "messages update perm update_own".
-- Dev's policy is strict on permission but checks `has_perm(..., 'message')` (singular).
-- Main's policy checks `has_perm(..., 'messages')` (plural) AND actor ownership.
-- NOTE: I will KEEP Main's update policy for now unless requested, as Dev's looks like a typo ('message').
-- However, if Dev works and Main fails, maybe the permission name IS 'message'?
-- Let's check the permissions table.
-- SELECT name FROM permissions WHERE resource = 'message' OR resource = 'messages';
-- But I can't pause the migration file creation to check.
-- I'll assume 'messages' (plural) is correct based on `20260129` migration file content.
-- I will NOT touch the update policy for authenticated users unless I'm sure.
-- The user complained about "message table" differences.
-- I'll stick to the clear wins (Insert, Select, File Link).

NOTIFY pgrst, 'reload schema';
