-- Migration: Sync Threads Table Policies to match Development
-- Generated by Antigravity to resolve policy discrepancy reported by user.
-- This aligns Main with Dev's simplified, scope-based RLS architecture.

-- 1. Sync INSERT policy (Relax to match Dev)
-- Dev has "threads insert perm create_channel_owned" which checks `is_master_agent_in_org` OR `channel.super_agent_id`.
-- Main has "threads insert perm create" which only checks `channel.super_agent_id`.
-- Dev's policy is MORE PERMISSIVE (allows Master Agents).
DROP POLICY IF EXISTS "threads insert perm create" ON public.threads;
DROP POLICY IF EXISTS "threads insert perm create_channel_owned" ON public.threads;

CREATE POLICY "threads insert perm create_channel_owned" ON public.threads
FOR INSERT TO authenticated
WITH CHECK (
  has_perm('create', 'threads') 
  AND (
    is_master_agent_in_org(org_id) 
    OR EXISTS (
      SELECT 1 FROM public.channels c 
      WHERE c.id = public.threads.channel_id 
      AND c.super_agent_id = auth.uid()
    )
  )
);

-- 2. Sync SELECT policy (Use scope function like Dev)
-- Main has separate "read_channel_owned", "read_collaborator".
-- Dev combines them into "threads select perm read super agent and members" using `can_access_channel_scope`.
DROP POLICY IF EXISTS "threads select perm read_channel_owned" ON public.threads;
DROP POLICY IF EXISTS "threads select perm read_collaborator" ON public.threads;
DROP POLICY IF EXISTS "threads select perm read super agent and members" ON public.threads;

CREATE POLICY "threads select perm read super agent and members" ON public.threads
FOR SELECT TO authenticated
USING (can_access_channel_scope(channel_id));

-- Note: "threads select perm read_all" is present in both and likely identical (simple permission check).
-- Note: "threads select anon web_widget" is present in both.
-- Note: "anon_threads_by_account" is present in both (synced in previous task).

-- 3. Sync DELETE policy
-- Dev has "threads delete perm delete_channel_owned" (Master Agent OR Owner).
-- Main has "threads delete perm delete_own" (Owner only).
DROP POLICY IF EXISTS "threads delete perm delete_own" ON public.threads;
DROP POLICY IF EXISTS "threads delete perm delete_channel_owned" ON public.threads;

CREATE POLICY "threads delete perm delete_channel_owned" ON public.threads
FOR DELETE TO authenticated
USING (
  has_perm('delete', 'threads')
  AND (
    is_master_agent_in_org(org_id)
    OR EXISTS (
      SELECT 1 FROM public.channels c 
      WHERE c.id = public.threads.channel_id 
      AND c.super_agent_id = auth.uid()
    )
  )
);

-- 4. Sync UPDATE policy
-- Dev has "threads update" (simple permission check `has_perm('update', 'threads')` both in USING and WITH CHECK).
-- Main has "threads update perm update_own" which enforces ownership.
-- Dev is significantly more relaxed (trusts permission system).
DROP POLICY IF EXISTS "threads update perm update_own" ON public.threads;
DROP POLICY IF EXISTS "threads update" ON public.threads;

CREATE POLICY "threads update" ON public.threads
FOR UPDATE TO authenticated
USING (has_perm('update', 'threads'))
WITH CHECK (has_perm('update', 'threads'));

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
